### ISSUE TITLE
Pre launch touchup

### ISSUE THREAD

**Issue by dblodorn** [public-assembly/neosound#36]
- [ ] Fix duplicates in filtered items
- [ ] Connect button passed into curation interface
- [ ] Curated by in grid view
- [ ] Style curation panel sizing
- [ ] IPFS gateway prop
- [ ] Escape button close popover
- [ ] Curate view mobile
- [ ] Mobile nav padding and font

**Comment by losingmyego** [comment]
Mobile menu 

- Extra padding on top
- Link containers cutting off letters 
- Font looks incorrect or stretched out, not sure


![IMG_BA6660F56767-1](https://user-images.githubusercontent.com/103976531/195184096-7eb8c16b-58af-4819-9f08-099859c553cb.jpeg)

**Comment by 0xTranqui** [comment]
adding in lodash as a platform level dependency to neosound to allow for easy shuffling of all the songs upon page load so that the order is different and the curation we are doing is less specific (just getting songs onto the platform, rather than determining order)

literally just implementing this pr on present material exactly https://github.com/0xTranqui/present-materials/pull/20/files#diff-aa98fd0757d0e1741503c50cfafb7726939d19819638bbe8e030a27adfec34a3

**Comment by 0xTranqui** [comment]
also comment from joey, lower priority but design wise they would prefer if the bottom play bar didnt show up until the first song is clicked

**Comment by 0xTranqui** [comment]
@dblodorn here is a higher priority one, thought I was on my way to fixing it but realizing it might need to be added into ther erc721drops minter component. Need to fix the crazy infinite supply number that shows up on open editions (see below)

<img width="792" alt="Screen Shot 2022-10-11 at 3 10 20 PM" src="https://user-images.githubusercontent.com/93691906/195188790-de08f235-7968-4de1-9c93-787d7a98c355.png">

here's the code I wrote for it before I realized thats its actually stuck in that component:

<img width="683" alt="Screen Shot 2022-10-11 at 3 11 07 PM" src="https://user-images.githubusercontent.com/93691906/195188922-44c468db-529b-4f01-b053-39781abec750.png">

**Comment by losingmyego** [comment]
update the favicon for neosound - file in slack
